apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-mysql
  namespace: db
  labels:
    app: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: 579349033092.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
        ports:
        - containerPort: 3306
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
