apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment-webapp
  namespace: app
  labels:
    name: webapp
    app: employees
spec:
  replicas: 3  # You can adjust the number of replicas as needed
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
      annotations:
        custom.dbport: "3306"  # Set the DBPORT value as an annotation
    spec:
      containers:
      - name: colorapp
        image: 579349033092.dkr.ecr.us-east-1.amazonaws.com/webapp:latest
        ports:
        - containerPort: 8080
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        - name: DBHOST
          value: "10.244.0.7"
        - name: DBPORT
          value: "3306"
        - name: DBPWD
          value: "password"
