apiVersion: v1
kind: Pod
metadata:
  name: pod-mysql
  namespace: db
  labels:
    name: pod-mysql
    app: mysql
spec:
  containers:
  - name: mysql
    image: 579349033092.dkr.ecr.us-east-1.amazonaws.com/mysql:latest
    ports:
    - containerPort: 3306
    env:
    - name: MYSQL_ROOT_PASSWORD
      value: "password"